#!/bin/bash

echo "🏠 House Server - 基于地图的房屋搜索系统演示"
echo "================================================"
echo ""

echo "🎯 新功能特色:"
echo "=================="
echo ""
echo "🗺️ 首页地图搜索:"
echo "  ✅ 页面打开就是地图搜索界面"
echo "  ✅ 顶部搜索框支持邮编、地址、关键字搜索"
echo "  ✅ 智能搜索建议和快速搜索标签"
echo "  ✅ 地图实时显示搜索结果"
echo "  ✅ 点击房屋标记查看详情"
echo ""
echo "🔍 搜索功能:"
echo "  ✅ 支持邮编搜索 (如: 92614, 92620)"
echo "  ✅ 支持地址搜索 (如: Harvard Ave, Yale Loop)"
echo "  ✅ 支持区域搜索 (如: Irvine, Newport Beach)"
echo "  ✅ 实时搜索建议下拉"
echo "  ✅ 快速搜索标签点击"
echo ""
echo "📍 地图功能:"
echo "  ✅ 所有房屋位置标记显示"
echo "  ✅ 价格标签悬停显示"
echo "  ✅ 点击标记查看房屋详情弹窗"
echo "  ✅ 地图/卫星视图切换"
echo "  ✅ 缩放控制和平移功能"
echo "  ✅ 自动定位到搜索结果区域"
echo ""
echo "📱 用户体验:"
echo "  ✅ 响应式设计，完美适配各种设备"
echo "  ✅ 现代化UI界面"
echo "  ✅ 流畅的交互动画"
echo "  ✅ 直观的操作方式"
echo ""

echo "🌐 访问地址:"
echo "============="
echo "  本地地址: http://localhost:3000"
echo "  网络地址: http://$(hostname -I | awk '{print $1}'):3000"
echo ""

echo "💡 使用指南:"
echo "============="
echo "  1. 打开浏览器访问 http://localhost:3000"
echo "  2. 在顶部搜索框输入搜索条件:"
echo "     - 邮编: 92614, 92620, 92612 等"
echo "     - 地址: Harvard Ave, Yale Loop 等"
echo "     - 区域: Irvine, Newport Beach 等"
echo "  3. 点击搜索按钮或按回车键"
echo "  4. 地图会自动定位并显示搜索结果"
echo "  5. 点击地图上的房屋标记查看详情"
echo "  6. 右侧侧边栏显示搜索结果列表"
echo "  7. 可以点击快速搜索标签快速搜索"
echo ""

echo "🎨 界面布局:"
echo "============="
echo "  📍 顶部: 搜索框和快速搜索标签"
echo "  🗺️ 左侧: 交互式地图显示"
echo "  📋 右侧: 搜索结果列表和统计"
echo "  💬 弹窗: 房屋详情信息"
echo ""

echo "🔧 技术特性:"
echo "============="
echo "  - Vue 3 + Composition API"
echo "  - Element Plus UI组件库"
echo "  - 响应式地图组件"
echo "  - 实时搜索和筛选"
echo "  - 距离计算和排序"
echo "  - 移动端完美适配"
echo ""

echo "📊 演示数据:"
echo "============="
echo "  - 5个Irvine房屋示例"
echo "  - 价格范围: $850,000 - $1,500,000"
echo "  - 房屋类型: House, Condo, Townhouse"
echo "  - 位置分布: Irvine各个区域"
echo ""

echo "🚀 开始体验基于地图的房屋搜索系统！"
echo ""
echo "按 Ctrl+C 停止演示"
echo ""

# 等待用户确认
read -p "按回车键继续..." 

echo "正在启动前端应用..."
echo ""

# 启动前端应用
cd frontend
npm run dev
