server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        
        - id: house-service
          uri: lb://house-service
          predicates:
            - Path=/api/houses/**
          filters:
            - StripPrefix=1
        
        - id: data-collection-service
          uri: lb://data-collection-service
          predicates:
            - Path=/api/data-collection/**
          filters:
            - StripPrefix=1
        
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.house.gatewayservice: DEBUG
